if (self.CavalryLogger) { CavalryLogger.start_js_script(document.currentScript); }

__d("oz-player/utils/OzError",[],(function(a,b,c,d,e,f){"use strict";a=function(a){babelHelpers.inheritsLoose(b,a);function b(b){var c;c=a.call(this,b.description)||this;c.$OzError1=b;c.name=b.type;c.message=b.description;b=c.stack;if(!(typeof b==="string"&&b!=="")){if(Error.captureStackTrace){var d={};Error.captureStackTrace(d,c.constructor);b=d.stack}else{d=new Error().stack.split("\n");d.splice(/^Error/.test(d[0])?1:0,1);b=d.join("\n")}typeof b==="string"&&b!==""?c.stack=b.replace(/^Error/,c.name):c.stack=""}return c}var c=b.prototype;c.getExtra=function(){return this.$OzError1.extra||{}};c.getType=function(){return this.$OzError1.type};c.getDescription=function(){return this.$OzError1.description};return b}(babelHelpers.wrapNativeSuper(Error));f["default"]=a}),66);
__d("VideoPlaybackQuality",[],(function(a,b,c,d,e,f){function a(a){if(typeof a.getVideoPlaybackQuality==="function")return a.getVideoPlaybackQuality().droppedVideoFrames;a=a.webkitDroppedFrameCount;return typeof a==="number"?a:0}function b(a){if(typeof a.getVideoPlaybackQuality==="function")return a.getVideoPlaybackQuality().totalVideoFrames;a=a.webkitDecodedFrameCount;return typeof a==="number"?a:0}f.getDroppedFrames=a;f.getTotalFrames=b}),66);
__d("VideoPlayerContextSensitiveConfigUtils",[],(function(a,b,c,d,e,f){"use strict";var g=function(a,b){return b.every(function(b){return a[b.name]===b.value})};a=function(a,b){return b.find(function(b){return g(a,b.contexts)})};f.getFirstMatchingValueAndContextTargets=a}),66);
__d("VideoPlayerContextSensitiveConfigResolver",["VideoPlayerContextSensitiveConfigPayload","VideoPlayerContextSensitiveConfigUtils","cr:1724253"],(function(a,b,c,d,e,f,g){"use strict";a=function(){function a(a){this.$1={},this.$2={},a==null?(this.$3=c("VideoPlayerContextSensitiveConfigPayload").static_values,this.$4=c("VideoPlayerContextSensitiveConfigPayload").context_sensitive_values):(this.$3=a.staticValues,this.$4=a.contextSensitiveValues)}var e=a.prototype;e.setContexts=function(a){this.$1=a,this.$2=this.$5(a)};e.getValue=function(a){if(this.$2[a]!=null)return this.$2[a];return this.$3[a]!=null?this.$3[a]:null};e.$5=function(a){var b=this;return Object.keys(this.$4).reduce(function(c,e){var f=b.$4[e];if(f!=null){f=d("VideoPlayerContextSensitiveConfigUtils").getFirstMatchingValueAndContextTargets(a,f);f!=null&&(c[e]=f.value)}return c},{})};a.getPayload=function(){return c("VideoPlayerContextSensitiveConfigPayload")};a.getSources=function(){return b("cr:1724253")};return a}();g["default"]=a}),98);
__d("VideoPlayerShakaGlobalConfig",["VideoPlayerContextSensitiveConfigResolver"],(function(a,b,c,d,e,f,g){var h=new(c("VideoPlayerContextSensitiveConfigResolver"))(),i={};a=function(a){i=a};b=function(a,b){if(!!i&&typeof i[a]==="boolean")return i[a];a=h.getValue(a);return a!=null&&typeof a==="boolean"?a:b};d=function(a,b){if(!!i&&typeof i[a]==="number")return i[a];a=h.getValue(a);return a!=null&&typeof a==="number"?a:b};e=function(a,b){if(!!i&&typeof i[a]==="string")return i[a];a=h.getValue(a);return a!=null&&typeof a==="string"?a:b};g.setGlobalOverrideConfig=a;g.getBool=b;g.getNumber=d;g.getString=e}),98);/*FB_PKG_DELIM*/
__d("CometRouteRenderType",["CometRouterRenderTypeContext","react"],(function(a,b,c,d,e,f,g){"use strict";var h=d("react").useContext;function a(){var a=h(c("CometRouterRenderTypeContext"));return a==="pushView"}function b(){var a=h(c("CometRouterRenderTypeContext"));return a==="hosted"}function e(){var a=h(c("CometRouterRenderTypeContext"));return a==="main"}g.useIsPushView=a;g.useIsHosted=b;g.useIsMain=e}),98);
__d("useParentRoute",["CometRouterParentRouteContext","react"],(function(a,b,c,d,e,f,g){"use strict";var h=d("react").useContext;function a(){return h(c("CometRouterParentRouteContext"))}g["default"]=a}),98);
__d("VideoHomeTypedLoggerLite",["generateLiteTypedLogger"],(function(a,b,c,d,e,f){"use strict";e.exports=b("generateLiteTypedLogger")("logger:VideoHomeLoggerConfig")}),null);